
services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    ports:
      - port: 10000
        protocol: http
